import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { renderApp, renderProject, sortApps, partitionProjects } from '../assets/catalog.js';
import { renderSupportPages, supportPath } from './support.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = path => readFile(resolve(root, path), 'utf8');
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const snapshot = JSON.parse(await read('data/apps.json'));
const web = JSON.parse(await read('data/projects.json'));
const groups = partitionProjects(web.projects);
const resources = JSON.parse(await read('data/app-support.json'));
for (const entry of resources.entries) {
  for (const key of ['privacy', 'terms', 'support']) {
    if (entry[key] && !(key === 'support' && entry.repairSupport)) await read(supportPath(entry[key]).slice(1));
  }
}
if (new Set(snapshot.apps.map(a => a.id)).size !== snapshot.apps.length) throw new Error('Duplicate apps');
if (new Set(web.projects.map(p => p.id)).size !== web.projects.length) throw new Error('Duplicate projects');
const source = await read('src/index.template.html');
const modules = ['assets/vendor/qrcodegen.js', 'assets/catalog.js', 'assets/qr.js', 'assets/galaxy.js', 'assets/site.js'];
const moduleSource = await Promise.all(modules.map(read));
const version = createHash('sha256').update(source + await read('assets/site.css') + await read('favicon.svg') + moduleSource.join('\n')).digest('hex').slice(0, 12);
const schema = { '@context': 'https://schema.org', '@type': 'Organization', name: 'Andromeda Kinship', url: 'https://andromedakinship.com/', logo: 'https://andromedakinship.com/assets/brand/andromeda-kinship.svg', email: 'info@andromedakinship.com', description: 'An independent studio and family of purposeful apps, useful websites, and source-backed data projects.', founder: { '@type': 'Person', name: 'Michael Dube' }, sameAs: ['https://apps.apple.com/us/developer/michael-dube/id1858655640', 'https://www.etsy.com/shop/AndromedaKinship'] };
const replacements = {
  VERSION: version, SCHEMA: json(schema), YEAR: snapshot.verifiedAt.slice(0, 4), PROJECT_COUNT: String(groups.website.length), PREVIEW_COUNT: String(groups.preview.length), APP_COUNT: String(snapshot.apps.length),
  VERIFIED_DATE: new Date(`${snapshot.verifiedAt}T12:00:00Z`).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }),
  PROJECTS: groups.website.map(renderProject).join('\n'), PREVIEWS: groups.preview.map(renderProject).join('\n'), APPS: sortApps(snapshot.apps).map(renderApp).join('\n'), APP_SNAPSHOT: json(snapshot), PROJECT_SNAPSHOT: json(web)
};
const output = source.replace(/\{\{([A-Z_]+)\}\}/g, (_, key) => { if (!(key in replacements)) throw new Error(`Unknown placeholder ${key}`); return replacements[key]; });
const supportPages = renderSupportPages(snapshot, resources, groups['app-support'], version);
const bundle = `// Generated by scripts/build.mjs. Edit the source modules, not this file.\n${moduleSource.map(code => code.replace(/^import .*;\n/gm, '')).join('\n')}`;
if (process.argv.includes('--check')) {
  if (await read('index.html') !== output) throw new Error('index.html is stale. Run npm run build.');
  if (await read('assets/site.bundle.js') !== bundle) throw new Error('JavaScript bundle is stale. Run npm run build.');
  for (const [path, content] of supportPages) if (await read(path) !== content) throw new Error(`${path} is stale. Run npm run build.`);
  console.log(`Static build current: ${groups.website.length} websites, ${groups.preview.length} previews, ${snapshot.apps.length} apps, ${supportPages.size} support pages.`);
} else {
  await writeFile(resolve(root, 'index.html'), output);
  await writeFile(resolve(root, 'assets/site.bundle.js'), bundle);
  for (const [path, content] of supportPages) await writeFile(resolve(root, path), content);
  console.log(`Built ${groups.website.length} websites, ${groups.preview.length} previews, ${snapshot.apps.length} apps, ${supportPages.size} support pages; asset version ${version}.`);
}
